name             'php_wrapper'
maintainer       'Pg Omni DevOps'
maintainer_email 'pg.omni.devops@lightspeedhq.com'
license          'Apache 2.0'
description      'Installs/Configures php_wrapper'
long_description 'Installs/Configures php_wrapper'
version          '3.2.0'
source_url       'https://github.com/lightspeedretail/chef-php-wrapper'
issues_url       'https://github.com/lightspeedretail/chef-php-wrapper/issues'

depends 'php', '~> 4.0.0'
